#!/usr/bin/python3

from app.rest import TreeRest
from app import test_cases
from app.checkers import CheckJql
from app.logger import logging
from colorama import Fore

log = logging.getLogger("main")


single_customfield = "customfield_10000"
multiple_customfield = "customfield_10001"
schema_id = 2

issue_data = {
    "fields": {
        "project": {"key": "TR"},
        "issuetype": {"id": "10000"},
        "description": "autogenerated"
    }
}


def main():
    with TreeRest(single_customfield, multiple_customfield, schema_id, issue_data) as inst:
        checker = CheckJql(inst)
        # checker.prepare_data(test_cases.eq_simple_cases)
        # checker.run()
        #
        # checker.prepare_data(test_cases.like_simple_cases)
        # checker.run()

        checker.prepare_data(test_cases.like_complex_cases)
        checker.run()

        for jql, errors in checker.errors.items():
            log.error(f"JQL: {jql}")
            for key, value in errors['matched']:
                log.error(f"{Fore.RED}Issue {key} with \"{value}\" founded, but should not!!!{Fore.RESET}")
            for key, value in errors['no_matched']:
                log.error(f"{Fore.RED}Issue {key} with \"{value}\" not founded, but should!!!{Fore.RESET}")
        input("press any key")


if __name__ == "__main__":
    main()
